// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirPath(arg1) {
  return window['go']['gtools']['App']['AddDirPath'](arg1);
}

export function AddTodoItem(arg1) {
  return window['go']['gtools']['App']['AddTodoItem'](arg1);
}

export function DelMdDir(arg1) {
  return window['go']['gtools']['App']['DelMdDir'](arg1);
}

export function GetDirList() {
  return window['go']['gtools']['App']['GetDirList']();
}

export function GetMdContent(arg1) {
  return window['go']['gtools']['App']['GetMdContent'](arg1);
}

export function NewMd(arg1, arg2) {
  return window['go']['gtools']['App']['NewMd'](arg1, arg2);
}

export function OpenMdSaveFileWindow() {
  return window['go']['gtools']['App']['OpenMdSaveFileWindow']();
}

export function OpenSelectFileWindow() {
  return window['go']['gtools']['App']['OpenSelectFileWindow']();
}

export function SaveMdContent(arg1, arg2) {
  return window['go']['gtools']['App']['SaveMdContent'](arg1, arg2);
}

export function StartTomcat() {
  return window['go']['gtools']['App']['StartTomcat']();
}

export function UploadScreenshot() {
  return window['go']['gtools']['App']['UploadScreenshot']();
}
