// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';
import {util} from '../models';
import {gtools} from '../models';

export function AddCmdItem(arg1:internal.CmdItem):Promise<util.Resp>;

export function AddMdDirPath(arg1:internal.MdPath):Promise<util.Resp>;

export function AddMdFile():Promise<util.Resp>;

export function AddTodoItem(arg1:internal.TodoItem):Promise<util.Resp>;

export function BaiDuTrans(arg1:string):Promise<util.Resp>;

export function BaiduOCR(arg1:number):Promise<util.Resp>;

export function CleanWebKitCache():Promise<util.Resp>;

export function CmdHandler(arg1:internal.CmdItem):Promise<util.Resp>;

export function DelCmdItem(arg1:internal.CmdItem):Promise<util.Resp>;

export function DelMdDir(arg1:internal.MdPath):Promise<util.Resp>;

export function DelTodoItem(arg1:internal.TodoItem):Promise<util.Resp>;

export function DelTodoItemById(arg1:internal.TodoItem):Promise<util.Resp>;

export function GetBdOCRToken():Promise<boolean|string>;

export function GetCmdItemList():Promise<util.Resp>;

export function GetConfigMap():Promise<{[key: string]: {[key: string]: string}}>;

export function GetConfigOnounted():Promise<util.Resp>;

export function GetMdContent(arg1:string):Promise<util.Resp>;

export function GetMdDirList():Promise<util.Resp>;

export function GetMdFileList(arg1:string):Promise<util.Resp>;

export function GetTodoItem(arg1:number):Promise<util.Resp>;

export function GetTodoList():Promise<util.Resp>;

export function NewMd(arg1:string,arg2:string):Promise<util.Resp>;

export function OpenMdFolderWindow():Promise<util.Resp>;

export function OpenMdSaveFileWindow():Promise<util.Resp>;

export function SaveImgPath():Promise<void>;

export function SaveMdContent(arg1:string,arg2:string):Promise<util.Resp>;

export function UpdateConfigByType(arg1:gtools.updatParam):Promise<util.Resp>;

export function UpdateConfigItem(arg1:internal.ConfigItem):Promise<util.Resp>;

export function UpdateTodoItem(arg1:internal.TodoItem):Promise<util.Resp>;

export function UploadScreenshot():Promise<util.Resp>;
