// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCmdItem(arg1) {
  return window['go']['gtools']['App']['AddCmdItem'](arg1);
}

export function AddMdDirPath(arg1) {
  return window['go']['gtools']['App']['AddMdDirPath'](arg1);
}

export function AddMdFile() {
  return window['go']['gtools']['App']['AddMdFile']();
}

export function AddTodoItem(arg1) {
  return window['go']['gtools']['App']['AddTodoItem'](arg1);
}

export function CleanWebKitCache() {
  return window['go']['gtools']['App']['CleanWebKitCache']();
}

export function DelMdDir(arg1) {
  return window['go']['gtools']['App']['DelMdDir'](arg1);
}

export function DelTodoItem(arg1) {
  return window['go']['gtools']['App']['DelTodoItem'](arg1);
}

export function DelTodoItemById(arg1) {
  return window['go']['gtools']['App']['DelTodoItemById'](arg1);
}

export function GetCmdItemList() {
  return window['go']['gtools']['App']['GetCmdItemList']();
}

export function GetMdContent(arg1) {
  return window['go']['gtools']['App']['GetMdContent'](arg1);
}

export function GetMdDirList() {
  return window['go']['gtools']['App']['GetMdDirList']();
}

export function GetMdFileList(arg1) {
  return window['go']['gtools']['App']['GetMdFileList'](arg1);
}

export function GetTodoItem(arg1) {
  return window['go']['gtools']['App']['GetTodoItem'](arg1);
}

export function GetTodoList() {
  return window['go']['gtools']['App']['GetTodoList']();
}

export function NewMd(arg1, arg2) {
  return window['go']['gtools']['App']['NewMd'](arg1, arg2);
}

export function OpenMdFolderWindow() {
  return window['go']['gtools']['App']['OpenMdFolderWindow']();
}

export function OpenMdSaveFileWindow() {
  return window['go']['gtools']['App']['OpenMdSaveFileWindow']();
}

export function OpenSelectFileWindow() {
  return window['go']['gtools']['App']['OpenSelectFileWindow']();
}

export function SaveMdContent(arg1, arg2) {
  return window['go']['gtools']['App']['SaveMdContent'](arg1, arg2);
}

export function StartTomcat() {
  return window['go']['gtools']['App']['StartTomcat']();
}

export function UpdateTodoItem(arg1) {
  return window['go']['gtools']['App']['UpdateTodoItem'](arg1);
}

export function UploadScreenshot() {
  return window['go']['gtools']['App']['UploadScreenshot']();
}
