// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirPath(arg1:string):Promise<string>;

export function DelMdDir(arg1:string):Promise<string>;

export function GetDirList():Promise<string>;

export function GetMdContent(arg1:string):Promise<string>;

export function GetWd():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenUrl(arg1:string):Promise<void>;

export function SaveMdContent(arg1:string,arg2:string):Promise<string>;

export function UploadImgByPicgo(arg1:string):Promise<string>;
