// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirPath(arg1) {
  return window['go']['main']['App']['AddDirPath'](arg1);
}

export function DelMdDir(arg1) {
  return window['go']['main']['App']['DelMdDir'](arg1);
}

export function GetDirList() {
  return window['go']['main']['App']['GetDirList']();
}

export function GetMdContent(arg1) {
  return window['go']['main']['App']['GetMdContent'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenUrl(arg1) {
  return window['go']['main']['App']['OpenUrl'](arg1);
}

export function SaveMdContent(arg1, arg2) {
  return window['go']['main']['App']['SaveMdContent'](arg1, arg2);
}

export function UploadScreenshot() {
  return window['go']['main']['App']['UploadScreenshot']();
}
