// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileList(arg1:string):Promise<string>;

export function GetMdContent(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function UploadImgByPicgo(arg1:string):Promise<string>;
