// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirPath(arg1) {
  return window['go']['main']['App']['AddDirPath'](arg1);
}

export function GetDirList() {
  return window['go']['main']['App']['GetDirList']();
}

export function GetMdContent(arg1) {
  return window['go']['main']['App']['GetMdContent'](arg1);
}

export function GetWd() {
  return window['go']['main']['App']['GetWd']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenUrl(arg1) {
  return window['go']['main']['App']['OpenUrl'](arg1);
}

export function UploadImgByPicgo(arg1) {
  return window['go']['main']['App']['UploadImgByPicgo'](arg1);
}
