// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileList(arg1) {
  return window['go']['main']['App']['GetFileList'](arg1);
}

export function GetMdContent(arg1) {
  return window['go']['main']['App']['GetMdContent'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UploadImgByPicgo(arg1) {
  return window['go']['main']['App']['UploadImgByPicgo'](arg1);
}
